fix bootstrap styles, fix pagination table appearance after item delete
Social-projects-Rivne/ICM pull request #29
Opened 2018-01-09 12:58 UTC by TrofimchukYarik

2018-01-09 13:00 UTC, gefasim approved these changes

2018-01-09 13:01 UTC, gefasim requested changes

2018-01-09 13:01 UTC, gefasim commented on src/main/resources/static/src/index.js
> -            <Route path="/" name="Client" component={Client}/>
Please restore this raw

2018-01-09 13:11 UTC, tzhenia approved these changes

2018-01-11 13:07 UTC, gefasim approved these changes

2018-01-11 13:07 UTC, merged

2018-01-11 13:10 UTC, tzhenia commented on src/main/resources/static/scss/_custom.scss
> +  margin-top: 2%;
don't use "margin-top: 2%"